---
deploy_username: deploy
deploy_password: "{{ server.deploy_password }}"
root_password: "{{ server.root_password }}"
logwatch_email: rjlynch86@googlemail.com
global_ruby_version: 2.3.0
ruby_versions:
  - 2.3.0

sites:
  - app_name: business_ideas
    url: businessideas.directory
    port: 3000
    db: business_ideas_production
    password: "{{ business_ideas.password }}"
