---
- name: Set up deploy user
  hosts: all
  remote_user: root
  roles:
    - common
  vars_files:
    - "private_vars/main.yml"

- name: Set up DB
  hosts: all
  remote_user: "{{ deploy_username }}"
  become: true
  roles:
    - db
  tags:
    - db
  vars_files:
    - "private_vars/main.yml"

- name: Set up Web
  hosts: all
  remote_user: "{{ deploy_username }}"
  become: true
  roles:
    - web
  tags:
    - web
  vars_files:
    - "private_vars/main.yml"
