---
- import_role:
    name: nginx

- name: Install git
  apt:
    name: git
    state: installed

- import_role:
    name: geerlingguy.redis

- import_role:
    name: rbenv-role

- name: Install nodejs
  apt:
    name: nodejs
    state: latest

- name: Make apps directory
  file:
    path: /var/www
    state: directory
    owner: "{{ deploy_username }}"

