---
- name: Change root password
  user:
    name: root
    password: "{{ root_password }}"

- name: Add authorised keys for root user
  authorized_key:
    user: root
    key: "{{ lookup('file', item) }}"
  with_items: "{{ ubuntu_common_deploy_public_keys }}"

- name: Add deploy user
  user:
    name: "{{ deploy_username }}"
    password: "{{ deploy_password }}"
    shell: /bin/bash
    generate_ssh_key: yes

- name: Copy deploy user public key
  fetch:
    src: "/home/{{ deploy_username }}/.ssh/id_rsa.pub"
    dest: "{{ deploy_username }}.pub"
    flat: yes
    fail_on_missing: yes

- name: Add authorised keys for deploy user
  authorized_key:
    user: "{{ deploy_username }}"
    key: "{{ lookup('file', item) }}"
  with_items: "{{ ubuntu_common_deploy_public_keys }}"

- name: Add deploy user to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ deploy_username }} ALL"
    line: "{{ deploy_username }} ALL=(ALL) NOPASSWD: ALL"
    state: present

- name: Update APT package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Update APT to latest packages
  apt:
    upgrade: safe

- name: Install required packages
  apt:
    state: installed
    pkg: "{{ item }}"
  with_items: "{{ ubuntu_common_required_packages }}"

- name: Install optional packages
  apt:
    state: installed
    pkg: "{{ item }}"
  with_items: "{{ ubuntu_common_optional_packages }}"

- name: Adjust APT update intervals
  copy:
    src: apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic

- name: Setup ufw
  ufw:
    state: enabled
    policy: deny

- name: Allow ssh traffic
  ufw:
    rule: allow
    port: "{{ ubuntu_common_ssh_port }}"
    proto: tcp

- name: Allow http traffic
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow https traffic
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Set up Postfix to relay mail
  debconf:
    name: postfix
    question: '{{ item.question }}'
    value: '{{ item.value }}'
    vtype: '{{ item.vtype }}'
  with_items:
    - { question: 'postfix/mailname', value: '{{ ansible_fqdn }}', vtype: 'string' }
    - { question: 'postfix/main_mailer_type', value: 'Internet Site', vtype: 'string' }

- name: Email log summay daily
  lineinfile:
    dest: /etc/cron.daily/00logwatch
    regexp: "^/usr/sbin/logwatch"
    line: "/usr/sbin/logwatch --output mail --mailto {{ logwatch_email }} --detail high"
    state: present
    create: yes

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

  #- name: Disallow root SSH access
  #  lineinfile:
  #    dest: /etc/ssh/sshd_config
  #    regexp: "^PermitRootLogin"
  #    line: "PermitRootLogin no"
  #    state: present
  #  notify: Restart ssh
