---
ubuntu_common_root_public_keys:
  - ~/.ssh/id_rsa.pub

ubuntu_common_deploy_public_keys:
  - ~/.ssh/id_rsa.pub

ubuntu_common_required_packages:
  - ufw
  - fail2ban
  - unattended-upgrades
  - logwatch

ubuntu_common_optional_packages:
  - vim

ubuntu_common_ssh_port: 22
